//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }

        [Display(Name ="Name")]
        public string ProductName { get; set; }

        [Display(Name ="Size")]
        public string ProductSize { get; set; }

        [Display(Name ="Quantity")]
        public Nullable<int> ProductQty { get; set; }

        [Display(Name ="Brand")]
        public string ProductBrand { get; set; }
        [Display(Name ="Image")]
        public string ProductPic { get; set; }
        
    }
}
